// <auto-generated />
using System;
using Database.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241207062500_Deplasare_Adaugare_Distanta")]
    partial class Deplasare_Adaugare_Distanta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.DataModels.Angajat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnp")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Marca")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cnp")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Marca")
                        .IsUnique();

                    b.ToTable("Angajati");
                });

            modelBuilder.Entity("Database.DataModels.Deplasare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AngajatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPlecare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSosire")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distanta")
                        .HasColumnType("int");

                    b.Property<double>("DstX")
                        .HasColumnType("float");

                    b.Property<double>("DstY")
                        .HasColumnType("float");

                    b.Property<Guid>("MasinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motiv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observatii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SrcX")
                        .HasColumnType("float");

                    b.Property<double>("SrcY")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AngajatId");

                    b.HasIndex("MasinaId");

                    b.ToTable("Deplasari");
                });

            modelBuilder.Entity("Database.DataModels.Masina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnFabricatie")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumarDeInmatriculare")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumarDeKilometri")
                        .HasColumnType("int");

                    b.Property<string>("SerieDeSasiu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NumarDeInmatriculare")
                        .IsUnique();

                    b.HasIndex("SerieDeSasiu")
                        .IsUnique();

                    b.ToTable("Masini");
                });

            modelBuilder.Entity("Database.DataModels.Deplasare", b =>
                {
                    b.HasOne("Database.DataModels.Angajat", "Angajat")
                        .WithMany()
                        .HasForeignKey("AngajatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.DataModels.Masina", "Masina")
                        .WithMany()
                        .HasForeignKey("MasinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angajat");

                    b.Navigation("Masina");
                });
#pragma warning restore 612, 618
        }
    }
}
